#!/bin/bash
# filepath: c:\Users\tobia\Documents\AI_Master\Second_Year\AI_Med\Assignments\Assignment1\ai4mi_project\train_segthor.job

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=TrainSEGTHOR
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --time=02:00:00
#SBATCH --output=slurm_outputs/slurm_output_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Navigate to your project directory
# cd $HOME/ai4mi_project/

# Activate your environment (adjust path as needed)
source activate ai4mi

# Run the training
python -O main.py --dataset SEGTHOR_CLEAN_SEED42 --mode full --epochs 25 --dest [DEST_FOLDER] --seed 42 --gpu 

# Print completion message
echo "Training completed! Check results in results/segthor/ce/"