#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=stat_test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=outputs/stat_test.out

module purge
module load 2023
module load Anaconda3/2023.07-2
source activate ai4mi

#python statistical_test.py --baseline_dir results/baseline --improved_dir results/augmented --dest results/augmented
python statistical_test.py --baseline_dir results/baseline --improved_dir results/loss/cedice --dest results/loss/cedice
python statistical_test.py --baseline_dir results/baseline --improved_dir results/loss/cedicebound --dest results/loss/cedicebound

