#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=stitch
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:20:00
#SBATCH --output=outputs/stitch.out

module purge
module load 2023
module load Anaconda3/2023.07-2
source activate ai4mi

python stitch.py --data_folder data/SEGTHOR_CLEAN/val/gt --dest_folder data/SEGTHOR_STITCHED/val/gt --num_classes 5 --grp_regex "(Patient_\d\d)_\d\d\d\d" --source_scan_pattern "data/segthor_train/train/{id_}/GT.nii.gz"
